### ISSUE TITLE
Integrate in main PRQL repo?

### ISSUE THREAD

**Issue by max-sixty** [prql/prql-code#6]
Would it make sense to merge this into the main repo? I'm thinking of adding some workflows, and there's some overlap. And keeping this extension on the same release as the main repo would ensure it's always up to date.

But OTOH, maybe there isn't much overlap between developers, given JS vs Rust? And cloning a huge repo to edit something small is a bit daunting?

Here's Malloy's, in their main repo: https://github.com/looker-open-source/malloy/tree/main/vscode-extension

@jiripospisil let me know if you have a view!

**Comment by jiripospisil** [comment]
Fine by me. I personally prefer monorepos.

**Comment by max-sixty** [comment]
I'm torn on this — I also prefer monorepos — but I worry that the main repo might be a bit daunting for folks who would otherwise be up for contributing here. The overlap of languages is low, given the rust vs js focus.

I'll leave this for the moment, set up the workflows here, and we can reassess as we go.
